on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundle
    - run: sudo apt-get install libsqlite3-dev
    - run: bundle install --jobs 4 --retry 3 --deployment
    - run: npm install
    - run: bundle exec rake
